In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("cleanedData.csv")
depNames = data['DepartmentCode'].unique()

daysData = pd.DataFrame()
timesData = pd.DataFrame()

for dep in depNames:
    daysArr = []
    timesArr = []
    sub_df = data[data['DepartmentCode'] == dep]
    for i, r in sub_df.iterrows():
        x = str(r['Days']).split(' ')
        if len(x[0])>1:
            x = list(x[0])
        for xx in x:
            daysArr.append(xx)
        timesArr.append(str(r['Time']).split('-')[0].strip().replace(" ", ""))
    daysCount = pd.DataFrame(pd.DataFrame(daysArr).groupby(0)[0].count())
    daysCount['dep'] = np.full((len(daysCount),), dep)
    daysCount.rename(columns={0: 'count'}, inplace=True)
    daysCount.reset_index(inplace=True)
    daysCount.rename(columns={0: 'days'}, inplace=True)
    days_order = ["M", "T", "W", "R", "F"]
    daysCount["days"] = pd.Categorical(daysCount["days"], categories=days_order, ordered=True)

    # Sort the DataFrame
    daysCount = daysCount.sort_values("days")



    
    daysData = pd.concat([daysData, daysCount])

    timesCount = pd.DataFrame(pd.DataFrame(timesArr).groupby(0)[0].count())
    timesCount['dep'] = np.full((len(timesCount),), dep)
    timesCount.rename(columns={0: 'count'}, inplace=True)
    timesCount.reset_index(inplace=True)
    timesCount.rename(columns={0: 'time'}, inplace=True)
    timesCount['time'] = pd.to_datetime(timesCount['time'], format='%I:%M%p')
    timesCount = timesCount.sort_values(by='time')
    timesCount['time'] = timesCount['time'].dt.strftime('%I:%M%p')
    timesData = pd.concat([timesData, timesCount])







#timesData.to_csv('timesData.csv', index=False)
#daysData.to_csv('daysData.csv', index=False)
daysData

   days  count       dep
1     M     42      ANTH
3     T     45      ANTH
4     W     46      ANTH
2     R     47      ANTH
0     F      9      ANTH
..  ...    ...       ...
0     F      8  W&L  CS
0     M    334      WRIT
2     T    227      WRIT
3     W    326      WRIT
1     R    228      WRIT

[395 rows x 3 columns]

In [6]:
dayTrendData = pd.read_csv("dayTrendData.csv")[500:550]
countDays = pd.DataFrame(columns=['Department','Quarter','# 1 Day','# 2 Days','# 3 Days','# 4 Days', '# 5 Days'])
dayTrendData

          CourseID Department   Days      Quarter
500    AS AM   127      AS AM    T R  Winter 2024
501    AS AM   128      AS AM    M W  Winter 2024
502    AS AM   130      AS AM    M W  Winter 2024
503    AS AM   186      AS AM    M W  Winter 2024
504   AS AM   194A      AS AM      W  Winter 2024
505    AS AM     8      AS AM    M W  Spring 2024
506    AS AM     9      AS AM    T R  Spring 2024
507    AS AM    71      AS AM    M W  Spring 2024
508  AS AM   100AA      AS AM    T R  Spring 2024
509    AS AM   111      AS AM    T R  Spring 2024
510    AS AM   127      AS AM    T R  Spring 2024
511    AS AM   133      AS AM    M W  Spring 2024
512    AS AM   136      AS AM    T R  Spring 2024
513    AS AM   151      AS AM    M W  Spring 2024
514    AS AM   157      AS AM    T R  Spring 2024
515    AS AM   160      AS AM    M W  Spring 2024
516    AS AM   184      AS AM    T R  Spring 2024
517   AS AM   194C      AS AM      W  Spring 2024
518    AS AM     1      AS AM    M W  Summer 2024
519    AS AM     2      AS AM    M W  Summer 2024
520    AS AM     8      AS AM    T R  Summer 2024
521    AS AM    71      AS AM    M W  Summer 2024
522  AS AM   100BB      AS AM    T R  Summer 2024
523   AS AM   101C      AS AM    M W  Summer 2024
524    AS AM   136      AS AM    T R  Summer 2024
525    AS AM   142      AS AM    M W  Summer 2024
526  AS AM   171AA      AS AM    T R  Summer 2024
527  AS AM   171BB      AS AM    T R  Summer 2024
528    AS AM   118      AS AM    TWR    Fall 2024
529    AS AM     1      AS AM    TWR  Winter 2025
530    AS AM   118      AS AM    TWR  Winter 2025
531    ASTRO     1      ASTRO    M W  Winter 2023
532    ASTRO     1      ASTRO  M W F  Spring 2023
533   ASTRO     1H      ASTRO      R  Spring 2023
534    ASTRO     1      ASTRO    M W  Summer 2023
535    ASTRO     1      ASTRO    M W    Fall 2023
536   ASTRO     1H      ASTRO      W    Fall 2023
537    ASTRO     1      ASTRO    T R  Winter 2024
538    ASTRO     1      ASTRO    T R  Spring 2024
539    ASTRO     2      ASTRO    M W  Spring 2024
540    ASTRO     1      ASTRO    T R  Summer 2024
541   ASTRO     1H      ASTRO      T  Summer 2024
542    ASTRO     2      ASTRO    M W  Summer 2024
543   BIOE    120B       BIOE    M W  Winter 2023
544   BIOE    120A       BIOE    M W  Spring 2023
545   BIOE    120B       BIOE    T R  Summer 2023
546   BIOE    120B       BIOE    T R    Fall 2023
547   BIOE    120A       BIOE    M W  Winter 2024
548    BIOE    101       BIOE      F  Summer 2024
549    BIOL CS  20       BIOL    M W  Winter 2023

In [5]:
dayTrendData = pd.read_csv("dayTrendData.csv")
countDays = pd.DataFrame(columns=['Department','Quarter','# 1 Day','# 2 Days','# 3 Days','# 4 Days', '# 5 Days'])

quarterList = ["Winter 2023", "Spring 2023", "Summer 2023", "Fall 2023",
               "Winter 2024", "Spring 2024", "Summer 2024", "Fall 2024", "Winter 2025"]

for dep in depNames:
    daysArr = []
    timesArr = []
    sub_df = dayTrendData[dayTrendData['Department'] == dep]
    for quar in quarterList:
        countList = [0,0,0,0,0]
        countArray = [dep]
        quarClass = sub_df[sub_df['Quarter'] == quar]
        for i, r in quarClass.iterrows():
            x = str(r['Days']).split(' ')
            if len(x[0])>1:
                x = list(x[0])
            countList[len(x)-1] += 1
        countArray.append(quar)
        for c in countList:
            countArray.append(c)
        countDays.loc[len(countDays)] = countArray
        

print(countDays)

    
countDays.to_csv('countDays.csv', index=False)

    Department      Quarter  # 1 Day  # 2 Days  # 3 Days  # 4 Days  # 5 Days
0         ANTH  Winter 2023        3         7         0         0         0
1         ANTH  Spring 2023        2         5         1         0         0
2         ANTH  Summer 2023        2        12         0         0         0
3         ANTH    Fall 2023        3        12         0         0         0
4         ANTH  Winter 2024        6         8         1         0         0
..         ...          ...      ...       ...       ...       ...       ...
724       WRIT  Winter 2024        1       114         0         0         0
725       WRIT  Spring 2024        1        98         0         0         0
726       WRIT  Summer 2024        1        87         0         0         0
727       WRIT    Fall 2024        0        11         0        15         0
728       WRIT  Winter 2025        0        18         1        20         0

[729 rows x 7 columns]